name: Deploy

permissions:
  contents: write

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - run: go version
      - run: mkdir -p dist
      - name: Build For Linux
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/hawkreq-linux_x86_64.exe ./cmd/hawkreq/
      - name: Build For Windows
        run: |
          GOOS=windows GOARCH=amd64 go build -o dist/hawkreq-windows_x86_64.exe ./cmd/hawkreq/
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist/
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            dist/*
